language: c++
sudo: required
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "AlwXbJjIpi5s3wzrx1+CYvVo4/OWHKRwFaLM5qG6oFxbza69HLySuNG5xvEK135QW+9LI56K109yj5y/JQ5YveDZ5C0bmxoE1wGkjXHSk/w9mI+hnr2Nn7WFwDZUfUM9y9e9r+4KTE5QCHxjXChlHf+7oJw48byLG9wWXgPH5u3S1ER3uADRWyV3xZXjApI71fviqw+EDDEDu2OQQmXgoXRWtLrmIto0xaWYRqars0i77mvJTop8HrR9pmOF+7RwM2txlHk2TOasDHtAOUITmjm5eNpYugoEZnpanC0P8Je5Kxz5g0enUBnB445XYyXR5UmcB2Esar+S++GeI6T7IViZpfoY0LND8OQZZEofFa+9p/kcH/guz5YDZA1jiXxzQWewsxEZ9FOku5IBtvcCZggQFf9qmiFKuiAPS1BrWzu5oNefEZ1LYn6UCdoI7kvhtCnBVX+doYjIBIHvAZleeYsWFv7Iuko9+BCKOewcSvzc0uK04zWG9XJFVckXYfw7omdH4rIMiUnYymB23Y2EtdDVIgxD4ayCoVfzv45pyzVNpitXtpgVAgbpePld7z9lnxJdw3T9x0GTWasc5e2G6BPMMwWBBQM9uS8K/vJxEHZD2F3hvPxZdGPMTkP82zlltQip5ba1zha8k8ZuvL1v1wTvI1NGE3CfXtja6o68OvE="
cache:
  directories:
    - /var/cache/apt/
    - /var/cache/pbuilder/aptcache/


matrix:
  include:

   # ###### Ubuntu Linux ####################################################

   # ====== Ubuntu 20.04 (Focal Fossa) ======================================
   - name: "Ubuntu 20.04 (Focal Fossa) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.04 (Focal Fossa) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.04 (Focal Fossa) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:focal" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 20.10 (Groovy Gorilla) ======================================
   - name: "Ubuntu 20.10 (Groovy Gorilla) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 20.10 (Groovy Gorilla) packaging with pbuilder"
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:groovy" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 18.04 (Bionic Beaver) ====================================
   - name: "Ubuntu 18.04 (Bionic Beaver) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 18.04 (Bionic Beaver) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 18.04 (Bionic Beaver) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 16.04 (Xenial Xerus) =====================================
   - name: "Ubuntu 16.04 (Xenial Xerus) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 16.04 (Xenial Xerus) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 16.04 (Xenial Xerus) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:xenial" VARIANT="ubuntu" TOOL="pbuilder"

   # ====== Ubuntu 14.04 (Trusty Tahr) ======================================
   - name: "Ubuntu 14.04 (Trusty Tahr) with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Ubuntu 14.04 (Trusty Tahr) with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Ubuntu 14.04 (Trusty Tahr) packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="ubuntu:trusty" VARIANT="ubuntu" TOOL="pbuilder"


    # ###### Debian Linux ###################################################

    # ====== Debian Testing =================================================
   - name: "Debian Testing with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Testing with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Testing packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:testing" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Sid ======================================================
   - name: "Debian Sid with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Sid with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Sid packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:sid" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Buster ===================================================
   - name: "Debian Buster with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Buster with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Buster packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:buster" VARIANT="debian" TOOL="pbuilder"

   # ====== Debian Stretch ==================================================
   - name: "Debian Stretch with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Debian Stretch with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Debian Stretch packaging with pbuilder"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="debian:stretch" VARIANT="debian" TOOL="pbuilder"


   # ###### Fedora Linux ###################################################

   # ====== Fedora 33 =======================================================
   - name: "Fedora 33 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 33 with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 33 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:33" VARIANT="fedora" TOOL="mock"

   # ====== Fedora 32 =======================================================
   - name: "Fedora 32 with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   - name: "Fedora 32 with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "Fedora 32 packaging with mock"
     os: linux
     dist: focal
     group: travis_latest
     env: DOCKER="fedora:32" VARIANT="fedora" TOOL="mock"

   # ====== Fedora Rawhide ==================================================
   # - name: "Fedora Rawhide with GCC"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
   # - name: "Fedora Rawhide with Clang"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   # - name: "Fedora Rawhide packaging with mock"
   #   os: linux
   #   dist: focal
   #   group: travis_latest
   #   env: DOCKER="fedora:rawhide" VARIANT="fedora" TOOL="mock"


   # ###### FreeBSD #########################################################

   # ====== FreeBSD 12.1-RELEASE ============================================
   - name: "FreeBSD 12.1-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.1-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.1-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 12.2-RELEASE ============================================
   - name: "FreeBSD 12.2-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.2-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 12.2-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="12.2-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"

   # ====== FreeBSD 11.4-RELEASE ============================================
   - name: "FreeBSD 11.4-RELEASE with Clang"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.4-RELEASE" TOOL="compile" COMPILER_C="clang" COMPILER_CXX="clang++"
   - name: "FreeBSD 11.4-RELEASE with GCC"
     os: linux
     dist: focal
     group: travis_latest
     env: QEMU="FreeBSD" VARIANT="11.4-RELEASE" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"


   # ###### Other ###########################################################

   # ====== MacOS X =========================================================
   # - name: "MacOS X"
   #   os: osx
   #   osx_image: xcode9.4
   #   compiler: clang
   #   group: travis_latest


   # ###### Special #########################################################

   - name: "Default Build"
     os: linux
     dist: focal
     group: travis_latest
     env: TOOL="compile"

   - name: "Coverity Scan"
     os: linux
     dist: focal
     group: travis_latest
     env:
      - TOOL="coverity"
      - VARIANT="ubuntu"
      - COVERITY_PROJECT="dreibh%2Fbibtexconv"
      - COVERITY_SCAN_NOTIFICATION_EMAIL="dreibh@simula.no"
      - COVERITY_SCAN_BRANCH="coverity_scan"


before_install:
  - ci/before-install

install:
  - ci/install

script:
  - ci/build
  - ci/test
