#!/usr/bin/env bash

# Bash options:
set -euo pipefail

while [ $# -gt 0 ] ; do
   f="$1"
   # shellcheck disable=SC2001
   n="$(echo "$f" | sed -e "s/\.[^\.]*$/.good/")"
   echo "$f -> $n"
   mv "$f" "$n"
   shift
done
