.\" BibTeX Converter
.\" Copyright (C) 2010-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd November 13, 2024
.Dt bibtexconv-odt 1
.Os bibtexconv-odt
.\" ###### Name #############################################################
.Sh NAME
.Nm bibtexconv-odt
.Nd ODT Helper Script for BibTeX Converter
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm bibtexconv-odt
Template_ODT
Output_ODT
BibTeX_File
Export_Script
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm bibtexconv-odt
runs bibtexconv to generate an Open Document Text (ODT) content.xml file, which
is then joined with an existing template ODT file into an output ODT file.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following arguments have to be provided:
.Bl -tag -width indent
.It Template_ODT
The template ODT file.
.It Output_ODT
The output ODT file.
.It BibTeX_File
The input BibTeX file for BibTeXConv.
.It Export_Script
The input export script for BibTeXConv.
.El
.\" ###### Arguments ########################################################
.Sh EXAMPLE
.Bl -tag -width indent
.It bibtexconv-odt \e
.br
/usr/share/doc/bibtexconv/examples/ODT-Template.odt \e
.br
MyPublications.odt \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
/usr/share/doc/bibtexconv/examples/odt-example.export
.br
Uses export script /usr/share/doc/bibtexconv/examples/odt-example.export to export references from /usr/share/doc/bibtexconv/examples/ExampleReferences.bib to MyPublications.odt as OpenDocument Text (ODT), according to the template ODT file /usr/share/doc/bibtexconv/examples/ODT-Template.odt.
.El
