.\" ==========================================================================
.\"                ____  _ _   _____   __  ______
.\"                | __ )(_) |_|_   _|__\ \/ / ___|___  _ ____   __
.\"                |  _ \| | '_ \| |/ _ \  / |   / _ \| '_ \ \ / /
.\"                | |_) | | |_) | |  __//  \ |__| (_) | | | \ V /
.\"                |____/|_|_.__/|_|\___/_/\_\____\___/|_| |_|\_/
.\"
.\"                          ---  BibTeX Converter  ---
.\"                   https://www.nntb.no/~dreibh/bibtexconv/
.\" ==========================================================================
.\"
.\" BibTeX Converter
.\" Copyright (C) 2010-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 29, 2025
.Dt bibtexconv 1
.Os bibtexconv
.\" ###### Name #############################################################
.Sh NAME
.Nm bibtexconv
.Nd BibTeX Converter
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm bibtexconv
BibTeX_file
.Op ...
.Op Fl B Ar bibtex_file_name | Fl Fl export-to-bibtex Ar bibtex_file_name
.Op Fl b Ar bibtex_file_prefix| Fl Fl export-\%to-\%separate-\%bibtexs Ar bibtex_\%file_\%prefix
.Op Fl X Ar xml_file_name | Fl Fl export-to-xml Ar xml_file_name
.Op Fl x Ar xml_file_prefix | Fl Fl export-\%to-\%separate-\%xmls Ar xml_\%file_\%prefix
.Op Fl C Ar custom_file_name | Fl Fl export-\%to-\%custom Ar custom_\%file_\%name
.Op Fl D Ar directory | Fl Fl store-downloads Ar directory
.Op Fl m Ar name:\%mapping_file:\%key_column:\%value_column | Fl Fl mapping Ar name:\%mapping_file:\%key_column:\%value_column
.Op Fl s Ar string | Fl Fl nbsp Ar string
.Op Fl l Ar string | Fl Fl linebreak Ar string
.Op Fl n | Fl Fl non-interactive
.Op Fl U | Fl Fl check-urls
.Op Fl u | Fl Fl only-check-new-urls
.Op Fl w | Fl Fl ignore-updates-for-html
.Op Fl a | Fl Fl add-url-command
.Op Fl i | Fl Fl skip-notes-with-isbn-and-issn
.Op Fl I | Fl Fl add-notes-with-isbn-and-issn
.Op Fl q | Fl Fl quiet
.Op Fl h | Fl Fl help
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm bibtexconv
is a BibTeX file converter which allows one to export BibTeX entries to other
formats, including customly defined text output. Furthermore, it provides the
possibility to check URLs (including MD5, size and MIME type computations) and
to verify ISBN and ISSN numbers.
.br
bibtexconv provides an interactive mode (usually used in form of export
scripts) which allows for fine-granular selection of entries, sorting and
export template specification.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following arguments may be provided:
.Bl -tag -width indent
.It BibTeX_File [...]
The BibTeX input file. Multiple files may be provided.
.It Fl B Ar bibtex_file_name | Fl Fl export-to-bibtex Ar bibtex_file_name
Write the results as BibTeX into the given file.
.It Fl b Ar bibtex_file_prefix| Fl Fl export-to-separate-bibtexs Ar bibtex_file_prefix
Write the results as BibTeX; for each entry, an own file will be created. The filename will be generated from given prefix (e.g. "/tmp/MyBibTex-"), the entry key and ".bib".
.It Fl X Ar xml_file_name | Fl Fl export-to-xml Ar xml_file_name
Write the results as XML (as used by IETF Internet Draft processing tools)
into the given file.
.It Fl x Ar xml_file_prefix | Fl Fl export-to-separate-xmls Ar xml_file_prefix
Write the results as XML; for each entry, an own file will be created. The filename will be generated from given prefix (e.g. "/tmp/MyBibTex-"), the entry key and ".xml".
.It Fl C Ar custom_file_name | Fl Fl export-to-custom Ar custom_file_name
Write the results as custom output into the given file.
.It Fl D Ar directory | Fl Fl store-downloads Ar directory
Combined with \-\-check-urls, all checked references are downloaded and stored in the given directory. Existing files will be overwritten.
.It Fl m Ar name:mapping_file:key_column:value_column | Fl Fl mapping Ar name:mapping_file:key_column:value_column
Read key and value columns from a mapping file into a mapping with given name.
.It Fl s Ar string | Fl Fl nbsp Ar string
Replace non-breakable space by given string (for example, "&nbsp;" when writing HTML).
.It Fl l Ar string | Fl Fl linebreak Ar string
Replace linebreak by given string (for example, "<br />" when writing HTML).
.It Fl n | Fl Fl non-interactive
Turns on non-interactive mode. Useful for just performing URL checks and
ISBN/ISSN verification.
.It Fl U | Fl Fl check-urls
Check URLs by downloading the content file and adding MD5, size and MIME type
entries.
.It Fl u | Fl Fl only-check-new-urls
Combined with \-\-check-urls, checks are only performed for new entries where
MD5, size and/or MIME type are still unknown.
.It Fl w | Fl Fl ignore-updates-for-html
Ignore changes in HTML files when checking URLs. This is useful for dynamically-generated web pages, where each retrieval creates a new, different HTML file.
.It Fl a | Fl Fl add-url-command
Add \\url{} commands to url tags in BibTeX export.
.It Fl i | Fl Fl skip-notes-with-isbn-and-issn
When reading the BibTeX file, ignore "note" items with ISBN and ISSN.
.It Fl I | Fl Fl add-notes-with-isbn-and-issn
When writing a BibTeX file, create "note" items with ISBN and ISSN.
.It Fl q | Fl Fl quiet
Reduces output verbosity.
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl Fl version
Prints program version.
.El
.\" ###### Commands #########################################################
.Sh COMMANDS
After startup, bibtexconv accepts the following commands from standard input
(not as command-line arguments!):
.Bl -tag -width ident
.It cite key [custom1 ... custom9]
Select specific entry in the input BibTeX file, given by key. Optionally, up
to nine custom strings may be attached to the selected entry.
.It citeAll
Select all entries in the input BibTeX file.
.It clear
Remove all selected citations, i.e. no citation will be selected.
.It sort key/[A|D] ...
Sort the selected citations, according to key and ascending (A) or
descending (D) ordering. The key corresponds to a key in the BibTeX file.
Multiple keys may be defined, e.g. sort year/D month/D day/D title/A.
.It echo string
Write given string to standard output.
.It export
Export selected entries to standard output, according to configured printing
template.
.It include file
Include another export script, given by file name.
.It monthNames jan feb mar apr may jun jul aug sep oct nov dec
Changes textual representation of month names. This is necessary when
non-English names are required for export.
.It nbsp
Changes textual representation of the "non-breakable space", for example
&nbsp; in HTML or ~ in BibTeX.
.It templatenew
Begin a new template definition. Initially, the template will be empty.
.It template+ template_string
Add the provided template string to the template. template+ allows one to define
a complex template consisting of multiple template+ lines, to enhance
readability. Within the template, the following placeholders can be used:
.Bl -tag -width ident
.It %{abstract}
Insert the BibTeX "abstract" content (i.e. the abstract of the publication).
.It %{address}
Insert the BibTeX "address" content (i.e. the address of the publication,
usually the conference or publisher location).
.It %{booktitle}
Insert the BibTeX "booktitle" content (i.e. the book title of the publication).
.It %{custom-1} | ... | %{custom-9}
Insert the corresponding value provided as custom1 ... custom9 to the "cite" command.
Some conversions may be applied when using "xmlStyle" (see below).
.It %{custom-1-as-is} | ... | %{custom-9-as-is}
Insert the corresponding value provided as custom1 ... custom9 to the "cite" command.
No conversions are applied.
.It %{day}
Insert the BibTeX "day" content (i.e. the publication day of the publication).
.It %{doi}
Insert the BibTeX "doi" content (i.e. the DOI number of the publication).
.It %{edition}
Insert the BibTeX "edition" content (i.e. the edition of the publication).
.It %{editor}
Insert the BibTeX "editor" content (i.e. the editor of the publication).
.It %{howpublished}
Insert the BibTeX "howpublished" content (i.e. the publication type of the publication).
.It %{institution}
Insert the BibTeX "institution" content (i.e. the institution of the publication).
.It %{isbn}
Insert the BibTeX "isbn" content (i.e. the ISBN of the publication).
.It %{issn}
Insert the BibTeX "issn" content (i.e. the ISSN of the publication).
.It %{issue}
Insert the BibTeX "issue" content (i.e. the issue of the publication).
.It %{journal}
Insert the BibTeX "journal" content (i.e. the journal containing the publication).
.It %{keywords}
Insert the BibTeX "keywords" content (i.e. the keywords of the publication).
.It %{language}
Insert the BibTeX "language" content (i.e. the language of the publication).
.It %{location}
Insert the BibTeX "location" content (i.e. the location of the publication,
usually the publisher location).
.It %{month}
Insert the BibTeX "month" content (i.e. the publication month of the publication).
.It %{note}
Insert the BibTeX "note" content (i.e. some additional information about the publication).
.It %{number}
Insert the BibTeX "number" content (i.e. the number of the publication).
.It %{numpages}
Insert the BibTeX "numpages" content (i.e. the number of pages of the publication).
.It %{organization}
Insert the BibTeX "organization" content (i.e. the organization of the publication).
.It %{pages}
Insert the BibTeX "pages" content (i.e. the pages range of the publication).
.It %{publisher} | %{$}
Insert the BibTeX "publisher" content (i.e. the publisher of the publication).
.It %{school}
Insert the BibTeX "school" content (i.e. the school of the publication).
.It %{series}
Insert the BibTeX "series" content (i.e. the series of the publication).
.It %{title}
Insert the BibTeX "title" content (i.e. the title of the publication).
.It %{type}
Insert the BibTeX "type" content (i.e. the type of the publication).
.It %{url}
Insert the BibTeX "url" content (i.e. the url of the publication).
.It %{url.checked}
Insert the BibTeX "url.checked" content. It contains the date of the last URL check.
This field is a custom field used by BibTeXConv.
.It %{url.keywords}
Insert the BibTeX "url.keywords" content. This field contains the keywords of the download from "url" (e.g. PDF keywords in a PDF file).
This field is a custom field used by BibTeXConv.
.It %{url.md5}
Insert the BibTeX "url.md5" content. It contains the MD5 sum of the download from "url".
This field is a custom field used by BibTeXConv.
.It %{url.mime}
Insert the BibTeX "url.mime" content. It contains the MIME type of the download from "url", e.g. "application/pdf" for PDF.
This field is a custom field used by BibTeXConv.
.It %{url.pagesize}
Insert the BibTeX "url.pagesize" content. It contains the paper format of the download from "url", e.g. "595.276 x 841.89 pts (A4)" for DIN A4 or "612 x 792 pts (letter)" for US Letter.
This field is a custom field used by BibTeXConv.
.It %{url.size}
Insert the BibTeX "url.checked" content. It contains the date of the last URL check.
This field is a custom field used by BibTeXConv.
.It %{content-language}
Insert the BibTeX "content-language" content. It contains the language of the actual publication content. For instance, "content-language" could be "chinese", while title and abstract (given by "language") is "english".
This field is a custom field used by BibTeXConv.
.It %{urn}
Insert the BibTeX "urn" content. This field contains the Uniform Resource Name (URN) number, used by many national libraries.
This field is a custom field used by BibTeXConv.
.It %{volume}
Insert the BibTeX "volume" content (i.e. the volume of the publication).
.It %{year}
Insert the BibTeX "year" content (i.e. the publication year of the publication).
.El
.Pp
The template allows the evaluation of blocks, with and without error containment:
.Bl -tag -width ident
.It [\~...\~]: Blocks with error containment
Blocks in square brackets are evaluated. If a referenced placeholder, e.g. %{url}, does not exist, the block will be emptied. This allows one to add content, e.g. the URL, if it exists in the BibTeX reference, but produce nothing if this information is unavailable.
.It (\~...\~): Blocks without error containment
Like [\~...\~], but if the evaluation fails, the failure is propagated to the next upper level. That is, a construct like [ ... (\~...\~)] will produce no output if the inner block evaluation fails (and therefore the parentheses propagate the failure to the next upper block). In contrast, [ ... [\~...\~]] would only result in an empty inner block.
.br
Note: Parentheses in the template need to be escaped, i.e. \[rs]( and \[rs]). Unescaped parentheses are interpreted as block definition!
.El
.Pp
Furthermore, by using blocks, some conditional evaluation is possible:
.Bl -tag -width ident
.It %{is?COMPARISON}
Success, if the block until the placeholder is equal to COMPARISON.
.It %{is-not?COMPARISON}
Success, if the block until the placeholder is not equal to COMPARISON.
.It %{is-less-than?COMPARISON}
Success, if the block until the placeholder is less than COMPARISON.
.It %{is-less-than-or-equal?COMPARISON}
Success, if the block until the placeholder is less than or equal COMPARISON.
.It %{is-greater-than?COMPARISON}
Success, if the block until the placeholder is greater than COMPARISON.
.It %{is-greater-than-or-equal?COMPARISON}
Success, if the block until the placeholder is greater or equal COMPARISON.
.It %{map:NAME}
Success, if the mapping NAME contains a mapping from the block until the placeholder. The block is evaluated to this mapping.
.El
.Pp
Finally, for handling the authors list of a publication, some special placeholders can be used:
.Bl -tag -width ident
.It %{begin-author-loop}
Begin loop over all authors. Within the loop, the following placeholders apply to the current author in the loop.
.It %{author-family-name}
Insert the current author's family name.
.It %{author-give-name}
Insert the current author's given name.
.It %{is-first-author?}
Success, if the current author is the first author.
.It %{is-not-first-author?}
Success, if the current author is not the first author.
.It %{is-last-author?}
Success, if the current author is the last author.
.It %{is-not-last-author?}
Success, if the current author is not the last author.
.It %{end-author-loop}
End the author loop started with %{begin-author-loop}.
.El
.It header header_string
Add the provided header string before each exported publication entry.
.It trailer trailer_string
Add the provided trailer string after each exported publication entry.
.It utf8Style
Use UTF-8 style conventions, i.e. export characters without conversion.
.It xmlStyle
Use XML style conventions, i.e. export characters with some conversions to
handle special characters not allowed in XML
(e.g. "&amp;" for "&", "&lt;" for <, etc.).
.El
.Pp
.\" ###### Arguments ########################################################
.Sh EXAMPLES
Have a look into /usr/share/doc/bibtexconv/examples/ (or corresponding path of
your system) for example export scripts. The export scripts contain the
commands which are read by bibtexconv from standard input.
.Bl -tag -width indent
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
\-\-export-to-bibtex=UpdatedReferences.bib \e
.br
\-\-check-urls \-\-only-check-new-urls \-\-non-interactive
.br
Checks URLs of all entries in /usr/share/doc/bibtexconv/examples/ExampleReferences.bib, adds MD5, size and MIME type
items and writes the results to UpdatedReferences.bib.
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
</usr/share/doc/bibtexconv/examples/web-example1.export >MyPublications.html
.br
Uses export script /usr/share/doc/bibtexconv/examples/web-example1.export to export references from /usr/share/doc/bibtexconv/examples/ExampleReferences.bib to MyPublications.html as XHTML 1.1.
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
</usr/share/doc/bibtexconv/examples/text-example.export >MyPublications.txt
.br
Uses export script /usr/share/doc/bibtexconv/examples/text-example.export to export references from /usr/share/doc/bibtexconv/examples/ExampleReferences.bib to MyPublications.txt as plain text.
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
</usr/share/doc/bibtexconv/examples/yaml-example.export >MyPublications.yaml
.br
Uses export script /usr/share/doc/bibtexconv/examples/yaml-example.export to export references from /usr/share/doc/bibtexconv/examples/ExampleReferences.bib to MyPublications.yaml as YAML file according to Debian Upstream MEtadata GAthered with YAml\~(UMEGAYA) format (see https://wiki.debian.org/UpstreamMetadata).
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
\-\-non-interactive \-\-export-to-separate-xmls=reference.
.br
Convert all references to XML references to be includable in IETF Internet Drafts. For each reference, an own file is generated, named with the prefix "reference.", for example reference.Globecom2010.xml for entry Globecom2010.
.It bibtexconv \e
.br
/usr/share/doc/bibtexconv/examples/ExampleReferences.bib \e
.br
\-\-non-interactive \-\-export-to-separate-bibtexs=
.br
Convert all references to BibTeX references. For each reference, an own file is generated, named with the prefix "", for example Globecom2010.bib for entry Globecom2010.
.El
