#!/usr/bin/Rscript --default-packages=utils
# $Id$
#
# Web example script to get HTML author URL from author in list
# Copyright (C) 2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

require(utils)

args <- commandArgs(TRUE)
if(length(args) != 3) {
   cat(file=stderr(), sep="", "Usage: get-author-url author_list author_name default_text\n")
   quit(status=1)
}

fileName     <- args[1]
authorName   <- gsub("&nbsp;", " ", args[2])
defaultText  <- args[3]
authorsTable <- read.table(fileName, header=TRUE)
authorIndex  <- which(authorsTable$Name == authorName)

if(length(authorIndex) == 0) {   # Case #1: the name is not in the table -> use default text
   cat(sep="", defaultText)
   quit()
} else if(length(authorIndex) > 1) {   # Case #2: the name is multiple times in the table -> warning
   cat(file=stderr(), sep="", "WARNING: Multiple occurences of name ", authorName, " in " , fileName, "!\n")
   authorIndex = authorIndex[1]
}

# Case #3: found the name -> print the result
cat(sep="", "<a href=\"", as.vector(authorsTable$URL)[authorIndex], "\">", as.vector(authorsTable$Name)[authorIndex], "</a>")
quit()
