#!/usr/bin/python
# -*- coding: utf-8 -*-
# $Id$
#
# Web example script to get HTML author URL from author in list
# Copyright (C) 2014 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

import codecs
import csv
import sys
import re;


# ====== Handle arguments ===================================================
if len(sys.argv) != 4:
   sys.stderr.write('Usage: get-author-url author_list author_name default_text\n')
   sys.exit(1)

replaceBbspStrings = re.compile(u'&nbsp;', re.UNICODE)

authorList = unicode(sys.argv[1], 'utf-8')
authorName = unicode(replaceBbspStrings.sub(u' ', unicode(sys.argv[2], 'utf-8')))
authorText = unicode(sys.argv[3], 'utf-8')

sys.stdout = codecs.getwriter('utf8')(sys.stdout)
sys.stderr = codecs.getwriter('utf8')(sys.stderr)
sys.stdin  = codecs.getreader('utf8')(sys.stdin)


# ====== Unicode wrapper for CSV reader =====================================
def unicode_csv_reader(unicode_csv_data, dialect=csv.excel, **kwargs):
    # csv.py doesn't do Unicode; encode temporarily as UTF-8:
    csv_reader = csv.reader(utf_8_encoder(unicode_csv_data),
                            dialect=dialect, **kwargs)
    for row in csv_reader:
        # decode UTF-8 back to Unicode, cell by cell:
        yield [unicode(cell, 'utf-8') for cell in row]

# ====== Unicode wrapper for CSV reader =====================================
def utf_8_encoder(unicode_csv_data):
    for line in unicode_csv_data:
        yield line.encode('utf-8')


# ====== Read CSV authors list ==============================================
csv.register_dialect('authors', delimiter=' ', quoting=csv.QUOTE_MINIMAL, skipinitialspace=True)

inputFile = codecs.open('authors.list', 'r', 'utf-8')
inputCSV = unicode_csv_reader(inputFile, dialect='authors')

# ====== Output HTML ========================================================
authorRow = None
for row in inputCSV:
   # print row
   if row[0] == authorName:
      if authorRow != None:
         # the authorName is multiple times in the table -> warning
         sys.stderr.write('WARNING: Multiple occurences of authorName ' + authorName + ' in ' + authorList + '!\n')
      authorRow = row


if authorRow == None:
   # The authorName is not in the table -> use default text
   sys.stdout.write(authorText)
   sys.stderr.write('NOTE: Did not find author name ' + authorName + ' in ' + authorList + '!\n')
   sys.exit(0)
else:
   # Found the authorName -> print the result
   sys.stdout.write('<a href="' + authorRow[1] + '">' + authorText + '</a>')
