.\" ==========================================================================
.\"                ____  _ _   _____   __  ______
.\"                | __ )(_) |_|_   _|__\ \/ / ___|___  _ ____   __
.\"                |  _ \| | '_ \| |/ _ \  / |   / _ \| '_ \ \ / /
.\"                | |_) | | |_) | |  __//  \ |__| (_) | | | \ V /
.\"                |____/|_|_.__/|_|\___/_/\_\____\___/|_| |_|\_/
.\"
.\"                          ---  BibTeX Converter  ---
.\"                   https://www.nntb.no/~dreibh/bibtexconv/
.\" ==========================================================================
.\"
.\" IETF2BibTeX
.\" Copyright (C) 2014-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd November 13, 2024
.Dt ietf2bibtex 1
.Os ietf2bibtex
.\" ###### Name #############################################################
.Sh NAME
.Nm ietf2bibtex
.Nd Create BibTeX entry for IETF document
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm ietf2bibtex
.Op Fl Fl quiet
.Op Fl Fl erbose
.Op Fl Fl authors-fix-file=NAME
.Op Fl Fl no-authors-fix-file
document
.Op document ...
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm ietf2bibtex
creates a BibTeX entry for an IETF document (i.e. RFC or Internet Draft). The
necessary information is automatically obtained from online XML references and
the actual document. Note, that author names are sometimes wrong, misspelled,
incomplete or inconsistent. Therefore, ietf2bibtex may read a file denoted as
authors fix file. It contains name translations in the form of
"Old Name" "New Name", for example:
.br
"A. Bundy"  "Al Bundy"
.br
"J. Muller" "Joe Müller"
.br
"J. Moller" "Jarle Møller"
.br
.br
Known limitations of ietf2bibtex:
.br
IETF metadata and documents only contain ASCII characters. To obtain the
correct non-ASCII author names (e.g. German, Norwegian, French, etc.), it
is necessary to use authors-fix.list.
.br
IETF metadata has often wrong or limited author information for a document.
ietf2bibtex tries to obtain the author information from the document.
Unusual formatting sometimes prevents this.
.br
IETF metadata often has the wrong date for a document.
ietf2bibtex tries to obtain the date from the document.
Unusual formatting sometimes prevents this.
.Pp
.\" ###### Arguments ########################################################
.Sh OPTIONS
The following arguments may be provided:
.Bl -tag -width indent
.It document
The name of the IETF document, e.g. like RFC5351 or
draft-dreibholz-mptcp-nornet-experience.
.It Fl Fl quiet
Print less progress information.
.It Fl Fl verbose
Print progress information (default).
.It Fl Fl authors-fix-file=NAME
Use the given file as authors fix file.
If not provided, the default is used: try authors-fix.list in the current
directory first, then /usr/share/doc/bibtexconv/examples/authors-fix.list.
.It Fl Fl no-authors-fix-file
Use no authors fix file.
.El
.Pp
.\" ###### Arguments ########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It ietf2bibtex RFC5351
.It ietf2bibtex RFC5351 RFC5352 RFC5353 RFC5354 RFC5355 RFC5356 RFC5525 >RSerPool.bib
.It ietf2bibtex --quiet draft-dreibholz-mptcp-nornet-experience
.It ietf2bibtex --verbose --authors-fix-file=/usr/share/doc/bibtexconv/examples/authors-fix.list draft-dreibholz-mptcp-nornet-experience
.El
