#!/bin/bash
# $Id$
#
# Copyright (C) 2002-2010 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -ne 4 ] ; then
   echo >&2 "Usage: make-odt [BibTeX file] [ODT template directory] [Export script] [ODT file]"
   exit 1
fi

TEMPDIR=`mktemp -d`
WORKDIR=$PWD

./bibtexconv $1 <$3 >$TEMPDIR/content.xml  && \
cp $2/meta.xml     $TEMPDIR && \
cp $2/mimetype     $TEMPDIR && \
cp $2/settings.xml $TEMPDIR && \
cp $2/manifest.rdf $TEMPDIR && \
cp $2/styles.xml   $TEMPDIR && \
mkdir $TEMPDIR/Configurations2 && \
mkdir $TEMPDIR/Configurations2/accelerator && \
cp $2/Configurations2/accelerator/current.xml $TEMPDIR/Configurations2/accelerator && \
mkdir $TEMPDIR/META-INF && \
cp $2/META-INF/manifest.xml $TEMPDIR/META-INF && \
mkdir $TEMPDIR/Thumbnails && \
cp $2/Thumbnails/thumbnail.png $TEMPDIR/Thumbnails && \
cd $TEMPDIR && \
zip odt-file.odt mimetype content.xml manifest.rdf styles.xml meta.xml Thumbnails/thumbnail.png Configurations2/accelerator/current.xml settings.xml META-INF/manifest.xml && \
mv odt-file.odt $WORKDIR/$4 && \
ls -l $WORKDIR/$4 && \
rm -rf $TEMPDIR && exit 0

exit 1
