#!/bin/bash
# $Id$
#
# Copyright (C) 2002-2010 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de

if [ $# -ne 4 ] ; then
   echo >&2 "Usage: make-odt [Template ODT] [Output ODT] [BibTeX file] [Export script]"
   exit 1
fi

TEMPLATE_ODT="$1"
OUTPUT_ODT="$2"
BIBTEX_FILE="$3"
EXPORT_SCRIPT="$4"

CONTENTSFILE="content.xml"


# TEMPDIR=`mktemp -d`
# WORKDIR=$PWD
#
# if [ ! -e "$TEMPDIR" ] ; then
#    echo >&2 "ERROR: Unable to create temporary directory!"
#    exit 1
# fi
#
# unzip q-d $TEMPDIR $2 && \
# ./bibtexconv $1 <$3 >$TEMPDIR/content.xml && \
# cd $TEMPDIR && \
# ls -lR


./bibtexconv $BIBTEX_FILE <$EXPORT_SCRIPT >$CONTENTSFILE && \
cp "$TEMPLATE_ODT" "$OUTPUT_ODT" && \
zip -r "$OUTPUT_ODT" content.xml


rm -f $CONTENTSFILE
