#!/bin/bash
# Export converter for web example
# $Id$

type="$1"
if [ "$type" = "authorUrl" ] ; then
   author="$2"
   authorText="$3"


   declare -A authorUrl
   authorUrl=(
      ["Thomas Dreibholz"]="http://www.exp-math.uni-essen.de/~dreibh/"
      ["Erwin Paul Rathgeb"]="http://www.tdr.wiwi.uni-due.de/team/erwin-p-rathgeb/"
      ["Michael Tüxen"]="https://www.fh-muenster.de/fb2/personen/professoren/tuexen/" 
      ["Martin Becke"]="http://www.tdr.wiwi.uni-due.de/team/martin-becke/"
      ["Hakim Adhari"]="http://www.tdr.wiwi.uni-due.de/team/hakim-adhari/"
      ["Ernst Gunnar Gran"]="https://simula.no/people/ernstgr"
      ["Amund Kvalbein"]="https://simula.no/people/amundk"
      ["Irene Rüngeler"]="https://www.fh-münster.de/fb2/personen/mitarbeiter/ruengeler/"
      ["Michael Striewe"]="http://paluno.uni-due.de/das-institut/team/wissenschaftliche-mitarbeiter/michael-striewe/"
      ["Özgü Alay"]="http://simula.no/people/ozgu"
      ["Robin Seggelmann"]="http://www.robin-seggelmann.de/"
      ["Simone Ferlin-Oliveira"]="http://simula.no/people/ferlin"
      ["Paul D. Amer"]="http://www.eecis.udel.edu/~amer/"
      ["Randall R. Stewart"]="http://people.freebsd.org/~rrs/"
      ["Jobin Pulinthanath"]="http://www.tdr.wiwi.uni-due.de/team/ehemalige-mitarbeiter/jobin-pulinthanath/"
      ["Andreas Jungmaier"]="http://www.tdr.wiwi.uni-due.de/team/ehemalige-mitarbeiter/andreas-jungmaier/"
      ["Carsten Hohendorf"]="http://www.tdr.wiwi.uni-due.de/team/ehemalige-mitarbeiter/carsten-hohendorf/"
      ["Sebastian Werner"]="http://www.tdr.wiwi.uni-due.de/team/sebastian-werner/"
      ["Markus Packeiser"]="http://www.tdr.wiwi.uni-due.de/team/markus-packeiser/"
      ["Daniel Bialla"]="https://www.uni-due.de/zim/organisation/mitarbeiterInnen/mitarbeiter_details.php?id=104"
      ["Dieter Huth"]="https://www.uni-due.de/zim/organisation/mitarbeiterInnen/mitarbeiter_details.php?id=35"
      ["Johannes Formann"]="http://dc.informatik.uni-essen.de/Formann/all/"
      ["Janardhan R. Iyengar"]="http://www.fandm.edu/janardhan-iyengar"
      ["Christian Henke"]="http://www.av.tu-berlin.de/menue/team/former_fellows/christian_henke/"
      # [""]=""
   )

   
   url="${authorUrl[` echo "$author" | sed -e "s/&nbsp;/ /g"`]}"
   if [ "$url" != "" ] ; then
      echo -n "<a href=\"$url\">$authorText</a>"
   else
      echo >&2 "WARNING: No URL for author $author"
      echo -n "$authorText"
   fi


elif [ "$type" = "location" ] ; then
   place="$2"
   
   if [ "$url" != "" ] ; then
      echo -n "<a href=\"$url\">$place</a>"
   else
      echo >&2 "WARNING: No URL for place $place"
      echo -n "$place"
   fi
fi
