#!/usr/bin/env bash
#
# Update BibTeX entries for IETF documents (RFCs and Internet Drafts)
# Copyright (C) 2014-2021 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@iem.uni-due.de
#

REFERENCES=~/src/papers/Referenzarchiv.bib
DOCUMENTS=`grep -E "^@[a-zA-Z]*{[ \t].*,.*$" "${REFERENCES}" | sed -e "s/,//g" | awk '{ print $2; }' | grep -E "^RFC|^draft"`
UPDATES_FILE="updated.bib"
RESULTS_FILE="results.bib"
PARALLEL=32


echo "Step 1: Fetching metadata ..."
echo "$DOCUMENTS" | (
   while read name ; do
      if [[ "${name}" =~ ^(RFC[0-9]+$)|(draft-[a-z].*$) ]] ; then
         # echo >&2 "Processing ${name} ..."
         echo "./ietf2bibtex --quiet \"${name}\" >${name}.bib"
      else
         echo "Skipping ${name}"
      fi
   done
) | parallel -j${PARALLEL}


echo "Step 2: Fetching documents ..."
echo "$DOCUMENTS" | (
   while read name ; do
      echo "./bibtexconv ${name}.bib -export-to-bibtex=${name}.bib2 -check-urls -only-check-new-urls -non-interactive"
   done
) | parallel -j${PARALLEL}


echo "Step 3: Collecting results ..."
cat ${REFERENCES} >${UPDATES_FILE}
echo "$DOCUMENTS" | (
   while read name ; do
      cat ${name}.bib2 >>${UPDATES_FILE}
      rm -f ${name}.bib ${name}.bib2
   done
)
./bibtexconv ${UPDATES_FILE} -export-to-bibtex=${RESULTS_FILE} -non-interactive
echo "Done."


diff ~/src/papers/Referenzarchiv.bib ${RESULTS_FILE} | grep -v url.checked | grep -v -E '^[[:alnum:]]+' | grep -v "^---$"
colordiff ${REFERENCES} ${RESULTS_FILE} |grep author|grep -B1 '>'
