# GitHub Actions Scripts
# Copyright (C) 2021-2022 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

name: Just a Test!

on:
  push:
    branches:
      - dreibh/test

jobs:
  manual-test:
    name: Manual Test
    runs-on: ubuntu-latest
    container:
      #image: ubuntu:22.04
      image: fedora:35
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: bash
        run: |
          CC=gcc CXX=g++ ARCH= ci/ci-setup   compile
          CC=gcc CXX=g++ ARCH= ci/ci-install compile
          CC=gcc CXX=g++ ARCH= ci/ci-build   compile
